'''
Created on 22-Nov-2019

@author: ragarwal
'''

financialDict = {"70 IT" : "Information Technology",
"IT - B&M" : "Information Technology",
"I9" : "Employment Eligibility Verification Form",
"I-9" : "Employment Eligibility Verification Form",
"108 IT" : "Information Technology",
"P&P" : "Patents",
"O&M" : "Operations",
"I.T":"Information Technology",
"IT":"Information Technology",
"6-K":"6-K form is one used by non-US based companies to disclose all information which is not covered in their quarterly / annual financial statements",
"8-K":"",
"1H":"1st Half",
"24/7":"24 hours a day, seven days a week",
"80/20":"for many events, roughly 80% of the effects come from 20% of the causes",
"AAA":"highest possible rating",
"AAGR":"Average Annual Growth Rate",
"ABS":"Asset Backed Security",
"AVB":"Actuals versus Budget",
"ABCP":"Asset-backed commercial paper",
"ADR":"American Depositary Receipt OR Average Daily Rate",
"ADS":"American depositary share",
"AI":"Artificial Intelligence",
"AIM":"Alternative Investment Market",
"ACH":"automated clearing house or automated clearinghouse",
"AJD":"Actos Jurídicos Documentados - stamp duty",
"Algo":"Algotithm",
"AM":"Account manager",
"AOP":"Adjusted Operating Profit",
"AOP":"Annual Operating Plan",
"AP":"Accounts payable",
"A/P":"Accounts payable",
"AR": "Accounts receivable",
"A/R": "Accounts receivable",
"APR":"Annual Percentage Rate",
"APY":"Annual Percentage Yield",
"APV":"Adjusted Present Value",
"AM":"Asset Management",
"AML":"Anti-money laundering",
"AML CO report":"AML Compliance officer report",
"AML RO or MLRO":"Money Laundering Reporting officer",
"APIC":"Additional Paid in Capital",
"ARPU":"Average revenue per user",
"ASP":"Average selling price",
"ASAP":"As soon as possible",
"AUM":"assets under management",
"AQL":"Acceptable Quaity Level",
"AAR":"Average Annual Return",
"agcy.":"Agency",
"agt.":"Agent",
"asst.":"Assistant",
"a/c.":"Account",
"A/D":"Advance or Decline line",
"afaik.":"As far as I know",
"BAU":"Business As Usual",
"BATNA":"Best Alternative to a Negotiated Agreement",
"BBSW":"Bank Bill Swap Rate",
"BCL":"Bank Confirmation Letter",
"BBB":"Better Business Bureau",
"BCP":"Business Continuity Planning",
"BEP":"Break Even Point",
"BEY":"Bond Equivalent Yield",
"BOT":"Balance of Trade",
"BOP":"Balance of Payment",
"BI":"Business Intelligence",
"BIC":"Bank Identifier Code",
"bldg.":"Building",
"BLS":"Balance Sheet",
"BMC":"Business Model Canvas",
"BOM":"Bill of Materials",
"BPO":"Business Process Outsourcing",
"BPR":"Brief Project Report",
"BPS":"Basis Point",
"BPV":"Bank Payment Voucher",
"BRD":"Business Requirements Document",
"BRU":"Business Recovery Unit",
"BRV":"Bank Receipt Voucher",
"BSA":"Bank Secrecy Act",
"BTW":"By the way",
"B2B":"Business-to-business",
"B2C":"Business to Consumer",
"B2G":"Business-to-government",
"BUSI":"Business",
"bus.":"Business",
"BV":"Book Value",
"BIMBO":"Buy-In Management Buyout",
"BRIC":"Brazil, Russia, India and China",
"BRICS":"Brazil, Russia, India, China and South Africa",
"BVPS":"Book Value Per Share OR Book Value of Equity Per Share",
"BV/Share":"Book Value Per Share OR Book Value of Equity Per Share",
"P/BV": "Price to Book Value",
"P/B":"Price to book",
"P/TBV":"price-to-tangible book",
"P/CF":"Price to cash flow",
"CAGR":"Compound annual growth rate",
"CAO":"Chief Administrative Officer or Chief Accounting Officer",
"CAP TABLE":"Capitalization Table",
"CAPA":"Corrective Action Preventive Action",
"CAPEX":"Capital Expenditure",
"CAPM":"Capital asset pricing model OR Cost of Equity",
"CBOE":"Chicago Board Options Exchange",
"CBOT":"Chicago Board of Trade",
"CCC": "Cash Conversion Cycle or Net Operating Cycle or Cash Cycle",
"CCE":"Cash and Cash Equivalents",
"CDO":"Collateralized debt obligation or Chief Data Officer",
"CDM":"Change and Data Management",
"CDS":"Credit default swap",
"CEI":"Collections Effectiveness Index or collector effective index",
"CPI":"Collection Productivity Index",
"CPA":"Cost per acquisition",
"CPC":"Cost-per-click",
"CPM":"Cost Per Thousand",
"CVP":"Cost-Volume-Profit",
"CEO":"Chief executive officer",
"COA":"Chart of Account",
"CFA":"Chartered Financial Analyst",
"CFP":"Certified Financial Planner",
"CFD":"Contract for difference",
"CFC":"Consumption of fixed capital or Controlled Foreign Corporation",
"CFCT":"Cash Flow Cycle Time",
"CFIUS":"Committee on Foreign Investment in the United States",
"CFM":"Certified Financial Manager",
"CFO":"Chief Financial Officer",
"CFS":"Consolidated Financial Statement or Cash Flow Statement",
"CIA":"Certified Internal Auditor",
"CIF":"Cost Insurance With Freight",
"CIM":"Confidential Information Memorandum",
"CIMA":"Chartered Institute of Management Accountants",
"CIO":"Chief Information Officer, Chief Innovation Officer or Chief Investment Officer",
"CIP":"Carriage and Insurance Paid",
"CIR":"Corporate Interest Restriction",
"CISA":"Certified Information Systems Auditor",
"CISO":"Chief Information Security Officer",
"CLA":"Chief Legal Officer",
"CCA":"Comparable Company Analysis",
"CMA":"Certified Management Accountant or Competition and Markets Authority",
"CML":"Capital Market Law",
"CMFB":"Committee on monetary, finance and balance of payments statistics",
"CMO":"Chief Marketing Officer",
"CMPO":"a confidentiality marketed public offering",
"COB":"Close of Business",
"CLO":"Collateralized Loan Obligation",
"COC":"Cost of Credit[2] or Cost of Capital[3]",
"COD":"Cost of Debt[4] or Cash on Delivery",
"COE":"Center of Excellence or Cost of Equity[5]",
"COGS":"Cost of Goods Sold",
"COS":"Cost of sales or cost of service",
"Corp.":"Corporation",
"COO":"Chief Operating Officer",
"COLA":"Cost-of-Living Adjustment",
"CPA":"Certified Public Accountant",
"CPI":"Consumer Price Index",
"CPO":"Chief People Officer also Chief Procurement Officer",
"CPQ":"Configure, Price, Quote",
"CPU":"Central Processing Unit",
"CRPC":"Chartered Retirement Planning Counselor",
"CSI":"Corporate Social Investment",
"CSO":"Chief Security Officer",
"CSR":"Corporate social responsibility",
"CTD":"Cheapest to Deliver",
"CRM":"Customer Relationship Management",
"CV":"Coefficient of Variation",
"CVA":"Cash Value added or Company Voluntary Arrangement",
"CVP":"Cost Volume Profit",
"CVR":"Contingent Value Rights",
"CCE":"Cash and Cash Equivalents",
"CTA":"Call to action or Cumulative Translation Adjustment",
"CTO":"Chief Technology Officer",
"CTR":"Currency Transaction report",
"CX":"Customer Experience",
"CXO":"Any chief officer(s), x being a placeholder.",
"C-Level":"roles of CEO, COO and CFO",
"C2B":"Consumer-to-business",
"C2C":"Customer to Customer",
"C&F":"Cost With Freight",
"CKM":"Customer Knowledge Management",
"CTC":"Cost to company or the Central Tenders Company",
"CUSIP number":"Committee on Uniform Security Identification Procedures number",
"Cr":"Credit",
"CA":"Current Account or Chartered Accountant",
"comps":"Comparable analysis",
"CML":"Capital Market Line",
"CO":"Certificate of Origin",
"CLN":"Credit Linked Note",
"CLTV":"Combined Loan-To-Value Ratio",
"CPG":"Consumer Packaged Goods",
"CPEC":"Convertible Preferred Equity Certificates",
"CFR":"Cost and Freight",
"COI":"Certificate of Insurance",
"CIT":"Corporate Income Tax",
"DAC":"Deferred Acquisition Costs",
"DKK":"Danish Krone",
"D&O INSURANCE":"Directors and Officers liablity insurance",
"DCM":"Debt Capital Market",
"DCF":"Discounted Cash Flow",
"DDA":"Depletion Depreciation Amortization",
"Dept.":"Department",
"DI":"Dispatch information",
"DIO":"Days of invetory outstanding or days sales of inventory",
"DSI": "Days Supply in Inventory",
"DII":"Days in Inventory or Inventory days",
"DIFOT":"Delivery in full on time, a variant of On Time In Full",
"Dir":"Director",
"disc.":"Discount",
"DMA":"Direct market access",
"DPA":"Definitive Purchase Agreement OR Stock Purchase Agreement or Definitive Merger Agreement",
"DPO":"Days Payable Outstanding or Direct Public Offering",
"DPS":"Dividend Per Share",
"DPSP":"Deferred Profit Sharing Plan",
"DRD":"Dividends Received Deduction",
"DRIP":"Dividend Reinvestment Plan",
"DCA":"Dollar-Cost Averaging",
"DR":"Depositary receipt or Depreciation rate",
"DSO":"Days Sales Outstanding",
"DSP":"Delivery service provider",
"DVP":"Delivery versus payment",
"D/E":"Debt to Equity shows the ratio of debt owed by a company compared to the equity value of the company",
"DOL":"Degree of Operating Leverage OR Department of Labor",
"DSCR":"Debt-service coverage ratio",
"EMS":"European Monetary System",
"EAR":"Effective annual rate",
"EAY":"Effective Annual Yield",
"EBIT":"Earnings before interest and taxes or Operating Profit",
"EBITA":"Earnings before interest and taxes and amortization",
"EBITDA":"Earnings before Interest, Taxes, Depreciation, and Amortization",
"EBITDAR":"Earnings before Interest, Taxes, Depreciation, Amortization and Rent",
"ECB":"European Central Bank",
"ECM":"Equity Capital Markets",
"EHM":"Efficient Market Hypothesis",
"EDI":"Electronic Data Interchange",
"EFSM":"European Financial Stabilisation Mechanism",
"EFSF":"The European Financial Stability Facility",
"e.g.":"For example",
"EFT":"Electronic Fund Transfer",
"EFTPOS":"Electronic Funds Transfer at Point of Sale",
"EPA":"Environmental Protection Agency",
"EPS":"Earnings per share",
"EXP":"Export",
"ETF":"Exchange Traded Fund",
"E&O insurance":"Errors and omissions insurance",
"EOB":"End of business",
"EOD":"End of day",
"EOM":"End of Message",
"ER":"Equity Research",
"ERP":"Enterprise Resource Planning",
"ERISA":"Employee Retirement Income Security Act",
"ETA":"Estimated Time of Arrival",
"etc":"Et Cetra",
"ETD":"Estimated Time of Departure or Estimated Time of Delivery or Exchange Traded Derivatives",
"EMI":"Equated Monthly Installment",
"EPC":"Export Promotion Council",
"EV":"Enterprise Value",
"EV/R":"enterprise value-to-revenue",
"EV / EBITDA":"it is the measure of the true value of a company (EV) in relation to the profitability of the company (EBITDA)",
"Debt / EBITDA":"financial ratios used in assessing the creditworthiness of a corporation",
"ECGC":"Export Credit Guarantee Corporation of India",
"EOS":"Economies of Scale",
"ESOP":"Employee Share Option Plan",
"ESPP":"Employee Stock Purchase Plan",
"EXW":"Ex Works",
"FAB":"Feature Advantage Benefits",
"FCF":"Free Cash Flow",
"FCFF":"Free Cash Flow to the Firm",
"FDP":"Finance Department",
"FOB":"Freight On Board",
"FI": "Fixed Income",
"FIFO":"First In, First Out",
"FinMin":"Finance Minister",
"Fin Min":"Finance Minister",
"FinCEN":"Financial Crimes Enforcement Network",
"FINRA":"Financial Industry Regulatory Authority",
"FL":"Financial leverage",
"FOMC":"Federal Open Market Committee",
"FP&A":"Financial Planning & Analysis",
"FPO":"Follow on public offer",
"FIX":"Financial Information Exchange",
"FSA":"Financial Services Authority",
"FV":"Future Value",
"FX":"Forex or Foreign exchange market",
"FY":"Fiscal year or Financial year",
"GAAP":"Generally Accepted Accounting Principles",
"GAAS":"Generally Accepted Audit Standards",
"GDP":"Gross Domestic Product",
"GNP":"Gross National Product",
"GDPR":"General Data Protection Regulation",
"GDR":"Global depository receipt",
"GFCF":"Gross fixed capital formation",
"GL":"General Ledger",
"GMV":"Gross Merchandise Volume",
"GP":"Gross Profit",
"GPO":"Group purchasing organization",
"GRN":"Goods Receipt Note",
"GRNI":"Goods Receipt Not Invoiced",
"GSV":"Gross Sales Value",
"GVC":"Global Value Chain",
"G&A":"General and Administration expense",
"T&E":"Travel and Entertainment expense",
"H1B":"H1B Visa is an employment-based, non-immigrant visa for temporary workers",
"HFT":"High Frequency Trading",
"HMRC":"Her Majesty's Revenue and Customs",
"HP":"Hire purchase",
"HQ":"Headquarters",
"HR":"Human Resources",
"HRD":"Human Resource Development",
"HS Code":"Harmonized Commodity Description and Coding System",
"IAS":"International Accounting Standards",
"IASB":"International Accounting Standards Board",
"IB":"Investment Bank",
"IR":"Interest Rate",
"IBAN":"International Bank Account Number",
"IBD":"Investment Banking Division",
"ICB":"Industry Classification Benchmark",
"ICRM":"Innovative Customer Relationship Management",
"IE":"Interest expense",
"IFRS":"International Financial Reporting Standard",
"ILCLP":"IdentLogic Systems Customer Loyalty Program",
"IMF":"International Monetary Fund",
"IMP":"Import",
"Inc.":"Incorporated",
"IoT":"Internet of Things",
"IP":"Intellectual Property",
"IPO":"Initial Public Offering",
"IPT":"Item Per Transaction",
"IR":"Interest Rate,typically referring to an IR derivative product",
"IRS":"Internal Revenue Service",
"IRR":"Internal Rate of Return",
"ISIN":"International Securities Identification Number",
"ISM":"Institute of Supply Management",
"ISDA":"International Swaps and Derivatives Association",
"ISS":"Institutional Shareholder Services",
"IU":"Irrevocable Undertaking",
"ITT":"Invitation to Tender",
"IYR":"In Year Revenue",
"IV":"Intrinsic Value",
"J":"Journal",
"JV":"Joint Venture",
"JIT":"Just in time",
"JIS":"Just in sequence",
"JST":"Joint Supervisory Team",
"KPI":"Key Performance Indicator",
"KYC":"Know Your Customer",
"large-cap":"large capitalization",
"LBO":"Leveraged Buyout",
"LF or LevFin":"Leveraged Finance",
"LC":"Letter of credit",
"LIBOR":"London Interbank Offered Rate",
"LE":"Latest Estimate",
"LIFFE":"London International Financial Futures and Options Exchange",
"LIFO":"Last In, First Out",
"LLC":"Limited Liability Company",
"LLLP":"Limited Liability Limited Partnership",
"LLP":"Limited Liability Partnership",
"LP":"Limited Partner or Limited Partnership",
"LME":"London Metal Exchange",
"LPT":"Liquidity Preference Theory",
"Ltd.":"Limited Company",
"LTV":"Loan to Value",
"LTV:CAC":"Lifetime Value(LTV) to Customer Acquisition Cost(CAC) The LTV/CAC ratio compares the value of a customer over their lifetime, compared to the cost of acquiring them",
"LoU":"Letters of Undertaking",
"mid-cap":"middle capitalization",
"MACD":"Moving Average Convergence Divergence",
"MA":"Moving Average",
"M&A": "Mergers and Acquisitions",
"MBO":"Management Buyout",
"MBI":"Management Buy-in",
"MFN":"Most Favored Nation",
"MGO":"Mandatory General Offer",
"MBT or MoBT":"Ministry of Business and Trade",
"MEBO":"Management and Employee Buyout",
"MoU":"Memorandum of Understanding",
"MVL":"Members Voluntary Liquidation",
"MBS":"mortgage-backed security",
"MD":"Managing Director",
"MER":"management expense ratio",
"mfg.":"Manufacturing",
"MGMT":"Management",
"MIC":"Market Identifier Code",
"MiFID":"Markets in Financial Instruments Directive",
"MILE":"Maximum impact, little effort [10]",
"MoM":"Month on Month / Month over Month or Multiple of Money",
"MOQ":"Minimum Order Quantity",
"MOE":"Merger of Equals",
"MIP":"Management Incentive Plan",
"MLP":"Master Limited Partnership",
"MNPI":"Material Non-Public Information",
"MPC":"marginal propensity to consume",
"MRO":"Maintenance, Repair, and Operations",
"MRP":"Maximum Retail Price OR materials requirement planning",
"MRR":"Monthly Recurring Revenue",
"MRR Churn or Churn MRR":"monthly recurring revenue lost due to customer cancellations",
"MSOD":"Monthly Statement of Select Operational Data",
"MSRP":"Manufacturer's Suggested Retail Price",
"MTD":"Month-to-date",
"MTM or M2M":"Mark to Market",
"MWC":"Managerial Working Capital",
"MPR":"Monthly Progress Report",
"NAV":"Net asset value",
"NCBO":"No Change of Beneficial Ownership",
"NCND":"Non-Circumvent and Non-Disclosure",
"NDA":"Non-Disclosure Agreement",
"NII":"Net Interest Income",
"NIM":"Net Interest Margin",
"No.": "Number",
"NOA":"Net Operating Assets",
"NOI":"Net Operating Income",
"NOL":"Net Operating Loss",
"NOMAD":"Nominated Adviser",
"NQDC Plan":"Non-qualified deferred compenation plan",
"NOPAT":"Net Operating Profit After Tax",
"NPA":"Non Performing Asset",
"NPL":"Non-performing loan",
"NPV":"Net Present Value",
"NTE":"Not To Exceed",
"NYSE":"New York Stock Exchange",
"OC":"Opportunity Cost or Offering Circular",
"OCF":"Operating cash flow",
"OCFD":"Operating cash flow demand",
"OEE":"Operational Effectiveness Rate",
"OECD":"Organisation for Economic Co-operation and Development",
"OEM":"Original Equipment Manufacturer",
"OFAC":"The office of foreign assets control",
"OIBDA":"Operating Income Before Depreciation And Amortization",
"OKR":"Objectives and key results",
"OOF":"Out of Facility, used interchangeably with Out of Office and originating from the Microsoft Xenix mail system [11]",
"OFT":"Office of Fair Trading",
"OOO":"Out of Office",
"OPEX":"Operating Expenditure or Operational Expenditure",
"OSHA":"Occupational Safety and Health Act",
"OTIF":"On Time In Full",
"OTC":"Over-the-counter (finance)",
"P&L":"PnL or Profit and Loss",
"P&S":"Purchase and Sale agreement",
"P2B":"Platform to Business [12]",
"P2P":"Public to Private",
"PA":"Purchasing agent or Personal Assistant",
"PA":"Promotional Activity[citation needed]",
"PAT":"Profit After Tax",
"PBT":"Profit Before Tax",
"PBGC":"Pension Benefit Guaranty Corporation",
"PD":"Prospectus Directive",
"P/E":"Price-to-earnings ratio",
"PE":"Private Equity",
"PEC":"Preferred Equity Certificate",
"PEG":"Price-to-earnings growth ratio",
"PHEK":"Planherstellungskosten (Product Planning cost)",
"PFI":"Private Finance Initiative",
"PI":"Professional Indemnity (insurance coverage)",
"PII":"Professional Indemnity (insurance coverage)",
"PII":"Personal identifiable information",
"PI":"Profitability index",
"pip":"Percentage in point",
"PIK":"Pay-in-kind",
"Pill":"Poison Pill",
"PIPE":"Private Investment in public equity",
"PMAC":"Period Moving Average Cost",
"PO":"Profit Objective or Purchase Order",
"POA":"Power of Attorney",
"POS":"Point of sale",
"PP&E":"Property, plant, and equipment",
"PPP":"Public-private partnership",
"PPP":"Purchasing power parity",
"PPT":"Powerpoint presentation",
"PR":"Purchase Requisition or Public Relations",
"Pro Supp":"Prospectus Supplement",
"PTD":"Project to Date",
"PUSU":"Put-up or Shut-up",
"PWIN":"Percent win (a measure of performance of capture when bidding for contracts with a targeted customer base such as bidding for government contracts) ",
"PWM":"Private Wealth Management",
"Q1, Q2, Q3, Q4":"quarters of the accounting year, calendar year or fiscal year",
"Q1": "quarters of the accounting year",
"Q2": "quarters of the accounting year",
"Q3": "quarters of the accounting year",
"Q4": "quarters of the accounting year",
"QC":"Quality control or Quality costs",
"QoQ":"Quarter on quarter",
"q/q":"Quarter Over quarter",
"QMS":"Quality Management System",
"QMV":"Qualified Majaority Voting",
"QS":"Quality System",
"QSP":"qualified stock purchase",
"QSR":"Quality System Regulation",
"QTD":"Quarter-to-date",
"RRR":"Required Rate of Return",
"RAQSCI":"Regulatory, Assurance of Supply, Quality, Service, Cost, Innovation",
"RBI":"Reserve Bank of India",
"RBA":"Reserve Bank of Australia",
"RE":"Retained Earnings",
"REPS": "Representatives or Sales Representatives",
"RECAP":"Recapitalization",
"Reps and Warranties":"representations and warranties",
"Retro":"Retroactive",
"RFI":"Request for information",
"RFP":"Request for Proposal",
"RFQ":"Request for Quotation",
"RFX":"Generic name for a Request for Information, Proposal or Quotation",
"ROA":"Return on assets",
"ROC":"Registration Of Company",
"ROCE":"Return on Capital Employed",
"ROE":"Return on Equity",
"ROI":"Return on Investment",
"ROIC":"Return on Invested Capital",
"RONA":"Return on net assets",
"ROS":"Return on Sales",
"RR":"Resource rent",
"REFI":"Refinance",
"RSP":"Retail selling price",
"RWA":"Risk-weighted asset",
"R&D":"Research and Development",
"RC":"Retail Company",
"SAR":"Suspicious Activity Report or stock appreciation rights",
"SE":"Shareholders Equity",
"St":"Sales, during time period t.",
"S&M":"Sales & Marketing",
"S&P":"Standard and Poors index",
"S&OP":"Sales and operations planning",
"SAAS":"Software-as-a-Service",
"SBU":"Strategic Business Unit",
"SBC":"Stock-Based Compensation",
"SBLC":"Stand By Letter of Credit",
"SCM":"Supply Chain Management",
"SCBA":"Social Cost Benefit Analysis",
"SEBI":"Securities and Exchange Board of India",
"SEC":"Securities and Exchange Commission",
"SEDOL":"Stock Exchange Daily Official List",
"SG&A":"Sales, General, and Administrative expenses or Operating Expenses",
"SIOP":"Sales Inventory and Operations Plan",
"SIR":"Stores Issuance Requisition",
"SIV":"Structured investment vehicle",
"SKU":"Stock keeping unit",
"SLA":"Service Level Agreement",
"SME":"Small and Medium Enterprises",
"small-cap":"small capitalization",
"SOHO":"Small Office/Home Office",
"SOP":"Standard Operating Procedure",
"SOW":"Statement of Work",
"SOX":"Sarbanes-Oxley Act",
"SROI":"Social return on investment",
"STP":"Situation Target Proposal or Situation Target Path [15]",
"SUA":"Start Up Agreement",
"TAA":"Trade Agreements Act",
"TB":"Transaction Banking",
"TBC":"To Be Completed",
"TBD":"To Be Defined",
"TCO":"Total Cost of Ownership",
"TCV":"Total Contract Value",
"TSR":"Total Shareholder Return",
"Ts & Cs":"Terms and Conditions",
"USP":"Unique Selling Proposition",
"UPI":"Unified Payment Interface",
"VAD":"Value-Added Distributor",
"VaR":"Value at Risk",
"CVaR":"Conditional Value at Risk",
"VAR":"Value-Added Reseller",
"VAT":"Value-Added Tax",
"VC":"Venture Capital",
"VP":"Vice President",
"vs.":"Versus",
"WACC":"Weighted average cost of capital",
"WC":"Working capital or Net Working Capital(NWC)",
"WFH":"Work From Home",
"wk":"week",
"wrk":"work",
"wo":"work order",
"WIGs":"Wildly Important Goals",
"wasp":"weighted average selling price",
"WLL":"With Limited Liability",
"w.r.t":"With Respect To",
"WTI":"West Texas Intermediate",
"WVN":"Withdraw Voucher Note",
"WHT":"Withholding Tax",
"WW":"World Wide",
"YTG":"Year-to-go",
"YTM":"Yield to Maturity",
"YTW":"Yield to worst",
"YOY":"Year-over-year",
"YTC":"Yet-To-Confirm",
"FYF":"Full Year Forecast",
"ZBB":"Zero Based Budgeting",
"zcyc":"Zero Coupon Yield Curve",
"ZOPA":"Zone of Possible Agreement",
"DTP":"Desktop Publishing",
"DTC":"Depository Trust Company",
"DTI":"Debt-to-Income Ratio",
"DIP":"Debtor in Possession",
"DIP Financing":"Debtor-in-Possession Financing",
"DD&A":"Depreciation, Depletion, and Amortization",
"FTE":"Full Time Equivalent",
"FYA":"For Your Action",
"FYI":"For Your Information",
"FOC":"Free Of Cost",
"F/U":"Follow-Up",
"FoF":"Fund of Funds",
"GMROII":"Gross Margin Return on Inventory Investment",
"NYMEX":"New York Mercantile Exchange",
"TOTW":"Time Off for Time Worked",
"TQM":"Total Quality Management",
"TTM":"Trailing Twelve Months",
"WTO":"World Trade Organization",
"WTD":"Week-To-Date",
"YTD":"Year-to-date",
"ECS":"Electronic Clearing Service or Electronic Clearing System",
"AR":"accounts receivable",
"AP":"accounts payable",
"ISO":"International Organization for Standardization OR Incentive Stock Option",
"CE":"Conformite Europeenne - CE label is legally required to appear on many types of products sold in those European countries to show that they meet European health, safety and environmental standards",
"UL or U/L":"Underwriters Laboratories",
"FCC":"Federal Communications Commission is the United States agency that regulates telecommunications",
"TS":"Technical Specification",
"Spec":"Specification or technical standard",
"Alpha":"one of the 5 technical risk ratios - used in trading to indicate risk-adjusted performance",
"Beta":"beta coefficients a term used in trading to indicate volatility or systematic risk of an asset compared to that of the overall market.",
"Delta":"Hedging ratio a term used in trading to compare the change in price of a derivative compared to the change in price of the underlying asset.",
"SD":"Standard deviation is a mathematical measure which approximates the average deviation of any given data point from the mean of the entire data set",
"EMH":"Efficient Market Hypothesis",
"HF":"Hedge Fund",
"CAC":"CAC40 is the benchmark index used in France",
"DAX":"The DAX is the benchmark index used in Germany",
"DJIA":"Dow Jones Industrial Average (commonly referred to as the Dow)",
"FTSE100":"Financial Times Stock Exchange is the benchmark index used in the United Kingdom",
"FTSE":"The Financial Times Stock Exchange Group",
"HSI":"Hang Seng INDEX is the benchmark index used in Hong Kong",
"NASDAQ":"National Association of Securities Dealers Automated Quotations System and is the world's second-largest stock exchange",
"ECB":"European Central Bank",
"EU":"European Union",
"EC":"European Community",
"EEC":"European Economic Area",
"EBA":"European Banking Authority",
"LSE":"The London Stock Exchange",
"U.K":"United Kingdom of Great Britain and Northern Ireland",
"UK":"United Kingdom of Great Britain and Northern Ireland",
"GBP":"pound sterling, is the official currency of the UK",
"BoE":"Bank of England",
"BOE":"Barrel Of Oil Equivalent",
"BOE/D":"Barrels Of Oil Equivalent Per Day",
"10-K":"annual report done by a company that gives a detailed rundown of its performance",
"10-Q":"quarterly report done by a company that gives a detailed rundown of its performance",
"8-K":"Form 8-K is required to announce major events relevant to shareholders",
"11-K":"SEC Form 11-K is the Annual Reports of Employee Stock Purchase, Savings, and Similar Plans",
"EURIBOR":"European Interbank Offer Rate",
"ESES":"Euroclear Settlement of Euronextzone Securities",
"LIFFE":"London International Financial Futures and Options Exchange is a futures exchange",
"EOI":"Expression of Interest",
"LOI": "Letter of Intent",
"SPA":"Share purchase agreement or a Sale and Purchase Agreement",
"APA":"Asset Purchase Agreement",
"VWAP":"Volume Weighted Average Price",
"MCS":"Market Value of Cash and Marketable securities",
"BI":"Beginning Inventory",
"EI":"Ending Inventory",
"FIFO":"First-in, first-out",
"LIFO":"Last-in, First-out",
"ARR":"Accounting Rate of return",
"BL or BoL":"Bill of Lading",
"SC":"Sales Price",
"TVC":"Total variable costs",
"EAC":"Equivalent Annual Cost",
"n":"Number",
"EOQ":"Economic Order Quantity",
"TFP":"Total Factor Productivity",
"FF&E":"Furniture, Fixtures, and Equipment",
"FFE":"Furniture, Fixtures, and Equipment",
"FF&A":"furniture, fixtures, and accessories",
"E-invoicing":"electronic invoicing",
"e-documents":"Electronic documents",
"WIP":"Work-in-progress or work in process",
"AIS":"Accounting Information Systems",
"SQL":"structured query language, a computer language commonly used for databases",
"DDB":"Double-declining balance method",
"NBV":"Net book value",
"NCI":"Non-controlling interest",
"FMV":"fair market value",
"BOD":"board of directors",
"B of D":"board of directors",
"EVE":"Economic Value of Equity",
"BVTA":"Book value of total assets",
"IA":"Intangible assets",
"CL":"Current Liabilities",
"STDO":"Short term debt obligations",
"RevPAR":"Revenue per available room",
"PB":"Payback period",
"DPP":"Discounted Payback Period",
"TVM":"time value of money",
"RoR":"Rate of Return",
"NIBCL":" non-interest bearing current liabilities",
"NOPAT":"Net operating profit after tax",
"MARR":"hurdle rate, OR minimum acceptable rate of return",
"PIRR":"Pooled internal rate of return",
"EVA":"economic value added",
"R(f)":"risk-free rate",
"ß":"Beta",
"EMRP":"Equity Market Risk Premium",
"βa​":"The beta of the security",
"Rrf​":"Risk-free rate",
"SVA":"Shareholder Value Added",
"WAI":"Wealth Added Index",
"MVA":"Market Value Added",
"DDM":"Divident Discount Model",
"FRB":"Federal Reserve Board",
"FRS":"Federal Reserve System",
"TAF":"Term Auction Facility",
"sisa":"stated income and stated asset loans",
"NINA":"no income/no asset loans",
"Forward P/E":"Price to forward earnings",
"P/EBITDA":"price-to-EBITDA",
"P/FCF":"price-to-free cash flow",
"LTM":"last 12 months or Latest 12 Months",
"NTM":"Next 12 Months",
"M/M":"month over month",
"∩":"intersection",
"IVI":"Initial value of investment",
"FVI":"Final value of investment",
"CFF":"Cash flow from financing activities",
"CfO":"Cash flow from operating",
"CFI":"Cash flow from operating",
"NPM":"Net profit margin",
"AT":"Asset turnover",
"EM":"Equity multiplier",
"DFL":"Degree of financial leverage",
"TIE":"Times interest earned",
"CBA":"Cost-benefit analysis",
"MR":"Marginal Revenue",
"MP":"Marginal Profit",
"MCMC":"Marginal Cost",
"ESG":"Environmental, social, and governance",
"SRI":"ocially responsible investment",
"QA":"Quantitative analysis OR Quality assurance",
"QC":"Quality Control",
"MD&A":"management discussion and analysis",
"CTR":"confidential treatment application or confidential treatment request",
"CTO":"confidential treatment order",
"IDR":"International Depository Receipt",
"ER":"Expense Ratio",
"GER":"Gross expense ratio",
"TER":"total expense ratio",
"LLCs":" limited liability companies",
"EV/2P ratio":"enterprise value (EV) divided by the proven and probable (2P) reserves",
"P2S Ratio":"Price-to-sales ratio",
"DPR":"Dividend Payout ratio",
"ICGR":"internal capital generation rate",
"CAR":"Contractors all risks insurance",
"ASO":"Administrative Services Only",
"TPA":"third-party administrators",
"QACAs":"Qualified Automatic Contribution Arrangements",
"EACA":"eligible automatic contribution arrangements",
"HCE":"highly compensated employees",
"NHCE":"non-highly compensated employees",
"ADP":"Actual Deferral Percentage",
"ACP":"Actual Contribution Percentage",
"RIA":"Registered Investment Advisor",
"IAR":"Investment Advisory Representative",
"EBSA":"Employee Benefits Security Administration",
"QPAM":"qualified professional asset manager",
"KPO":"Knowledge process outsourcing",
"CNAR":"compound net annual rate",
"AAGR":"average annual growth rate",
"AER":"annual equivalent rate",
"RORAC":"return on risk-adjusted capital",
"RAROC":"Risk-adjusted return on capital",
"RARORAC":"risk-adjusted return on risk-adjusted capital",
"BCAR":" Best's Capital Adequacy Relativity",
"OL":"Operating losses",
"AGM":"Annual General Meeting",
"ACGM":"Autorità Garante della Concorrenza e del Mercato - The Italian Competition Authority",
"AD&D":"Accidental Death and Dismemberment Insurance",
"ARM":"Adjustable-Rate Mortgage",
"AGI":"Adjusted Gross Income",
"AIRB":"Advanced internal rating-based",
"ADR":"American Depositary Receipt",
"ADS":"American Depositary Share",
"ABB":"Activity-Based Budgeting",
"ABC":"Always Be Closing or Activity-Based Costing",
"ATR":"Average True Range",
"AOTC":"American Opportunity Tax Credit",
"ATO":"Assemble to Order",
"BaaS":"Blockchain-as-a-Service",
"e-commerce":"Electronic Commerce",
"e-tailing":"Electronic retailing",
"CIF":"Cost, Insurance and Freight",
"RM Inventory":"Raw Material Inventory",
"WIP Inventory":"Work in Progress inventory",
"FG inventory":"Finished Goods inventory",
"FMLA":"Family and Medical Leave Act",
"USG":"United States Government",
"Workers Comp":"Workers' compensation",
"SDSs":"Safety Data Sheets",
"DBA, dba, d.b.a. or d/b/a":"doing business as",
"AULs":"Activity and Use limitations",
"HVAC":"Heating, ventilation, and air conditioning",
"EH&S":"Environment, Health, and Safety",
"YE":"Year End",
"circled R":"indicates federal registration",
"®":"indicates federal registration",
"(R)":"indicates federal registration",
"(r)":"indicates federal registration",
"little capital letters TM (™)":"trademark",
"little capital letters SM (℠)":"service mark",
"© symbol or Copr.":"Copyright",
"WAF":"web application firewalls",
"DNS":"Domain Name Server",
"2FA":"Two Factor Authentication",
"CDN":"Content Delivery Network",
"TCWG":"Transportation Conformity Working",
"UCC":"Uniform Commercial Code",
"EEOC":"Equal Employment Opportunity Commission",
"FTC":"Federal Trade Commission",
"DOJ":"Department of Justice OR Justice Department",
"PPE":"Personal protective equipment",
"USPTO":"United States Patent and Trademark Office",
"cc":"Carbon Copy",
"bcc":"Blind Carbon Copy",
"w/o":"Without or Write off",
"PM":"the Prime Minister OR=r Project Manager",
"MPs":"A member of parliament",
"WTO":"The World Trade Organization",
"GATT":"General Agreement on Tariffs and Trade",
"DUP":"Euroskeptic Democratic Unionist Party",
"EIB":"European Investment Bank",
"(MIL) .MI":"The Milan Stock Exchange, known in Italian as the Borsa Italiana, is Italy’s only stock exchange",
"PAR":"The Paris Stock Exchange, now know as the NYSE Euronext",
"NYX":"The Paris Stock Exchange, now know as the NYSE Euronext",
"CAC 40 Index":"Consumer Advisory Council",
"ICE":"Intercontinental Exchange",
"ISE":"Irish Stock Exchange",
"EUREX":"Eurex Exchange",
"EEX":"European Energy Exchange",
"WBAG":"Vienna Stock Exchange",
"FRA":"Frankfurt Stock Exchange",
"AMEX":"The American Stock Exchange",
"FTA":"Free Trade Agreements",
"FATA":"Foreign Acquisitions and Takeovers Act",
"Business EC":"Exemption certificates for business acquisitions",
"GST":"Goods and services tax",
"CGT":"Capital gains tax",
"CCA":"Competition and Consumer Act",
"ASX":"Australian Securities Exchange",
"ASIC":"Australian Securities & Investments Commission",
"ETAs":"The Commonwealth, State and Territory Electronic Transactions Acts",
"ACCC":". The Australian Competition and Consumer Commission",
"AUD":"The Australian dollar",
"FIRB":"Foreign Investment Review Board",
"ATO":"Australian Taxation Office",
"CDR":"Consumer Data Right",
"NPP":"New Payments Platform",
"CET1":"Common Equity Tier 1",
"FRTB":"Fundamental Review of the Trading Book",
"IRRBB":"Interest Rate Risk in the Banking Book",
"IBOR":"Interbank Offer Rate",
"IMA":"Internal Modelling Approach",
"ASPAC":"Asia Pacific",
"PMI":"Post-merger integration",
"13e-3 Deal":"Going private transactions",
"13e-3 transaction":"Going private transactions",
"280G":"US Internal Revenue code section that provides for the loss of tax deductions by the company",
"280G Gross Up":"A Gross up for the excise tax penalty resulting under 280G",
"338(h)(10) election":"An election to treat a stock acquisition of the target corporation generally as an asset acquisition for US federal income tax purposes",
"ABI":"Association of British Insurers",
"MAC":"Material Adverse Change",
"Business MAE":"Business Material Adverse Effect",
"C in C":"Change in Control",
"COC":"Change of Control",
"COMI":"Centre of Main Interests",
"CompAcq":"Comparable Acquisition Analysis",
"CompCo":"Comparable Company Analysis",
"PECs":"Convertible Preferred Equity Certificate",
"PCOs":"Pollution Control Officers",
"CP":"Condition Precedent",
"CREST":"Central Depository for holding Uncertificated UK or Irish Securities or Electronic share trading settlement system used in UK or Ireland",
"CRO":"Companies Registration Office",
"EDGAR":"Electronic Data Gathering, Analysis and Retrieval system",
"EEA":"European Economic Area",
"CFIUS":"Committee on Foreign Investment in the United States",
"FCA":"UK Financial Conduct Authority",
"FCPA":"Foreign Corrupt Practices Act",
"PRA":"UK Prudential Regulation Authority",
"HSR":"Hart-Scott-Rodino Act",
"IBC":"Independent Board Committee",
"IBES":"Institutional Brokers Estimate System",
"I/B/E/S":"Institutional Brokers Estimate System",
"IBO":"Institutional Buy-out",
"IFA":"Independent Financial Advisor",
"IR":"Investor Relations",
"LTIP":"Long Term Incentive Plan",
"NED":"Non-executive Director",
"OM":"Offering Memorandum",
"OPD":"Opening Position Disclosure",
"GT&C":"General Terms and Conditions",
"T&Cs":"Terms and Conditions",
"T&C":"Terms and Conditions",
"HNTE Status":"High- and New-Technology Enterprise",
" O&M costs":"The Operation and Maintenance costs",
"telex transfer":"telegraphic transfer",
"T/T bank payment ":"telegraphic transfer",
"RMP":"Risk Management Plan",
"PSM":"Process Safety Management",
"VDD":"A vendor due diligence",
"EIR":"The effective interest rate or Establishment Inspection Report"}